/*QUESTION 13 */

SELECT DISTINCT ONAME
FROM OWNERP1, OWNS2, WORKS_ON2, PLANETYPE2, MAINTAIN1, EMPLOYEE2
WHERE OWNERP1.ID = OWNS2.ID 
AND OWNS2.REGNO = PLANETYPE2.REGNO 
AND PLANETYPE2.MODEL = WORKS_ON2.MODEL
AND WORKS_ON2.SSN = EMPLOYEE2.SSN 
AND MAINTAIN1.SSN = WORKS_ON2.SSN 
AND MAINTAIN1.SERVICE_ID = PLANETYPE2.REGNO