/*QUESTION 14*/
SELECT OWNERP1.ONAME, OWNERP1.PHONENO
FROM OWNERP1, HANGAR1, OWNS2
WHERE OWNERP1.ID = OWNS2.ID
AND OWNERP1.OTYPE = 'Corporation'
AND HANGAR1.REGNO = OWNS2.REGNO
AND HANGAR1.LOCATIONS = OWNERP1.ADDRESS