/*QUESTION 15*/
SELECT DISTINCT PILOT1.NAMEP
FROM PILOT1
JOIN EMPLOYEE2 ON EMPLOYEE2.SSN = PILOT1.SSN
JOIN FLIES1 ON PILOT1.LIC_NUM = FLIES1.LIC_NUM
JOIN PLANETYPE2 ON FLIES1.MODEL = PLANETYPE2.MODEL
JOIN AIRPLANE1 ON PLANETYPE2.REGNO = Airplane1.REGNO
JOIN PLANE_SERVICE ON AIRPLANE1.REGNO = PLANE_SERVICE.REGNO
JOIN MAINTAIN1 ON PLANE_SERVICE.SERVICE_ID = MAINTAIN1.SERVICE_ID
WHERE MAINTAIN1.SSN = PILOT1.SSN;