/*QUESTION 16 */
SELECT EMPLOYEE2.ENAME
FROM EMPLOYEE2
JOIN WORKS_ON2 ON EMPLOYEE2.SSN = WORKS_ON2.SSN
JOIN PLANETYPE2 ON WORKS_ON2.MODEL= PLANETYPE2.MODEL
JOIN OWNS2 ON PLANETYPE2.REGNO = OWNS2.REGNO
JOIN OWNERP1 ON OWNS2.ID = OWNERP1.ID
JOIN MAINTAIN1 ON EMPLOYEE2.SSN = MAINTAIN1.SSN
JOIN SERVICE2 ON SERVICE2.SERVICE_ID = MAINTAIN1.SERVICE_ID

WHERE OWNERP1.OTYPE = 'Corporation'
--GROUP BY EMPLOYEE2.ENAME
ORDER BY SERVICE2.SHOURS DESC