/*QUESTION 17*/
SELECT DISTINCT  PLANETYPE2.MODEL,PLANETYPE2.REGNO
FROM PLANETYPE2
INNER JOIN OWNS2 ON PLANETYPE2.REGNO = OWNS2.REGNO
INNER JOIN OWNERP1 ON OWNS2.ID = OWNERP1.ID
INNER JOIN PLANE_SERVICE ON OWNS2.REGNO = PLANE_SERVICE.REGNO
INNER JOIN MAINTAIN1 ON PLANE_SERVICE.SERVICE_ID = MAINTAIN1.SERVICE_ID
INNER JOIN EMPLOYEE2 ON MAINTAIN1.SSN = EMPLOYEE2.SSN
WHERE OWNERP1.OTYPE != 'Corporation'
OR
(EMPLOYEE2.SSN=MAINTAIN1.SSN AND EMPLOYEE2.SHIFTTYPE='Day')