/*QUESTION 18*/
SELECT DISTINCT ONAME, OWNERP1.ADDRESS
FROM OWNERP1, OWNS2, PLANETYPE2
WHERE OWNERP1.ID = OWNS2.ID AND PLANETYPE2.REGNO = OWNS2.REGNO AND OTYPE = 'Corporation' AND
PDATE > DATEADD(MONTH, -1, GETDATE())
ORDER BY ONAME