/*Question 6 */
 
SELECT TOP 5 EMPLOYEE2.SSN, ENAME, SERVICE2.SHOURS 
FROM EMPLOYEE2
INNER JOIN MAINTAIN1
ON EMPLOYEE2.SSN = MAINTAIN1.SSN
INNER JOIN SERVICE2
ON MAINTAIN1.SERVICE_ID = SERVICE2.SERVICE_ID
ORDER BY SHOURS
DESC