/*QUESTION 7*/
SELECT PLANETYPE2.MODEL, PLANETYPE2.REGNO
FROM PLANETYPE2
INNER JOIN PLANE_SERVICE
ON PLANETYPE2.REGNO = PLANE_SERVICE.REGNO
INNER JOIN SERVICE2
ON PLANE_SERVICE.SERVICE_ID=SERVICE2.SERVICE_ID
WHERE SERVICE2.SDATE BETWEEN DATEADD(day, -7, GETDATE()) And GETDATE();